config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :opinions
  post 'images' => 'images#create'
  get 'tags/:tag', to: 'books#index', as: :tag

  get 'images/index'
  get 'images/new'
  get 'images/show'
  resources :books do
    resources :coms
    member do
      get 'tags/:tag',to: "books#index"

      put "add", to: "books#library"
      put "remove", to: "books#library"
      # get "show", to: "books#show"
    end
  end
  resources :library, only:[:index]
  resources :pricing, only:[:index]

  devise_for :users, controllers: { registrations: "registrations" }
  as :user do
    get '/users/sign_out' => 'devise/sessions#destroy'

    root to: 'books#index'
    resources :subscriptions
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/book.rb
class Book < ApplicationRecord
  has_attached_file :image,
  :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
  :url => "/system/:attachment/:id/:style/:filename",
  :styles => { :medium => "500x500>", :thumb => "120x90#" },
  :default_url => "path to default image"

  validates_attachment_content_type :image, content_type: /\Aimage/

  belongs_to :user

    has_many :libraries
    has_many :added_books, through: :libraries, source: :user
    has_many :coms, :dependent => :destroy
    has_many :taggings
    has_many :tags, through: :taggings

    def self.tagged_with(name)
    Tag.find_by!(name: name).books
  end

  def self.tag_counts
    Tag.select("tags.id, tags.name,count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id, tags.id, tags.name")
 end


  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end


end

app/models/com.rb
class Com < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/image.rb
class Image < ApplicationRecord
  attr_accessible :image, :book
has_attached_file :image
validates_attachment_file_name :image, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/]
end

app/models/library.rb
class Library < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :books, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :books, dependent: :destroy
    has_many :libraries
    has_many :library_additions, through: :libraries, source: :book
  
  def connection
  letsrate_rater
end

def subscribed?
  stripe_subscription_id?
end


end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy library]
  before_action :authenticate_user!, except: %i[index show]

  # GET /books
  # GET /books.json
  def index
    @books = if params[:tag]
               Book.tagged_with(params[:tag])
             else
               Book.all
             end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    # @book = Book.find(params[:id])
    @com = Com.new
    @com.book_id = @book.id
  end

  # GET /books/new
  def new
    @book = current_user.books.build
  end

  # GET /books/1/edit
  def edit; end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.build(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def as_json(options = {})
    super(options.merge(include: [:user, comments: { include: :user }]))
  end

  # add and remove books from/to library
  def library
    type = params[:type]

    if type == 'add'
      current_user.library_additions << @book
      redirect_to library_index_path, notice: "#{@book.title} was added to your library"
    elsif type == 'remove'
      current_user.library_additions.delete(@book)
      redirect_to root_path, notice: "#{@book.title} was removed from your library"
    else
      # type is missing, nothing happens
      redirect_to book_path(@book), notice: 'Looks like nothing happend'
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def book_params
    params.require(:book).permit(:title, :description, :author, :user_id, :image, :tag_list)
  end

  def com_params
    params.require(:com).permit(:body, :user_id)
  end
end

app/controllers/coms_controller.rb
class ComsController < ApplicationController

  def create
    @com = Com.new(com_params)
    @com.book_id = params[:book_id]
    @com.save
    redirect_to book_path(@com.book)

      end


 def as_json(options = {})
    super(options.merge(include: :user))
  end


  def com_params
    params.require(:com).permit(:body, :user_email)
  end


end

app/controllers/pricing_controller.rb
class PricingController < ApplicationController
  layout "subscribe"

  def index
  end
end 

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user_subscribed?
    user_signed_in? && current_user.subscribed?
  end

  def admin?
    user_signed_in? && current_user.admin?
  end

  def subscribed?
    user_signed_in? && current_user.subscribed?
  end


  def tag_cloud(tags, classes)
      max = tags.sort_by(&:count).last
      tags.each do |tag|
        index = tag.count.to_f / Integer(max.count) * (classes.size - 1)
        yield(tag, classes[index.round])
      end
    end


      def titlize(str)
        str.gsub('_', ' ').capitalize
      end
end

app/helpers/books_helper.rb
module BooksHelper
  def user_added_to_library? user, book
    user.libraries.where(user: user, book: book).any?
  end

  end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/coms_helper.rb
module ComsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/views/pricing/index.html.erb
  <div class="has-text-centered box">
    <h1 class="title">Pricing</h1>
    <h3 class="subtitle">Choose the best plan that matches your reading consistency and budget.</h3>
    <h2>Choosing a plan is not obligatory</h2>
    <a href="<%= root_path %>" class="button is-primary">Homepage</a><br><br>

    
    <div class="pricing-table">
      <div class="pricing-plan is-warning">
        <div class="plan-header">Starter</div>
        <div class="plan-price"><span class="plan-price-amount"><span class="plan-price-currency">$</span>5</span>/month</div>
        <div class="plan-items">
          <div class="plan-item">5 Downloads</div>
        </div>
        <div class="plan-footer">
          <% if user_signed_in? %>
            <%= link_to 'Subscribe', new_subscription_path(plan: "starter", plan_id: "plan_E5UXHyW0QqPKfB"), class:"button is-fullwidth" %>
          <% else %>
            <%= link_to 'Subscribe', new_user_registration_path, class: 'button is-fullwidth' %>
         <% end %>
        </div>
      </div>
      <div class="pricing-plan is-link is-active">
        <div class="plan-header">Book Worm</div>
        <div class="plan-price"><span class="plan-price-amount"><span class="plan-price-currency">$</span>10</span>/month</div>
        <div class="plan-items">
          <div class="plan-item">10 Downloads</div>
        </div>
        <div class="plan-footer">
           <% if user_signed_in? %>
            <%= link_to 'Subscribe', new_subscription_path(plan: "book_worm", plan_id: "plan_E5UXTmJntEgUuW"), class:"button is-fullwidth" %>
          <% else %>
            <%= link_to 'Subscribe', new_user_registration_path, class: 'button is-fullwidth' %>
         <% end %>
        </div>
      </div>
      <div class="pricing-plan is-danger">
        <div class="plan-header">Scholar</div>
        <div class="plan-price"><span class="plan-price-amount"><span class="plan-price-currency">$</span>30</span>/month</div>
        <div class="plan-items">
          <div class="plan-item">30 Downloads</div>
        </div>
        <div class="plan-footer">
         <% if user_signed_in? %>
            <%= link_to 'Subscribe', new_subscription_path(plan: "scholar", plan_id: "plan_E5UY1hATDzz4Il"), class:"button is-fullwidth" %>
          <% else %>
            <%= link_to 'Subscribe', new_user_registration_path, class: 'button is-fullwidth' %>
         <% end %>
        </div>
      </div>
    </div>
  </div>