config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :opinions
  post 'images' => 'images#create'
  get 'tags/:tag', to: 'books#index', as: :tag

  get 'images/index'
  get 'images/new'
  get 'images/show'
  resources :books do
    resources :coms
    member do
      get 'tags/:tag',to: "books#index"

      put "add", to: "books#library"
      put "remove", to: "books#library"
      # get "show", to: "books#show"
    end
  end
  resources :library, only:[:index]
  resources :pricing, only:[:index]

  devise_for :users, controllers: { registrations: "registrations" }
  as :user do
    get '/users/sign_out' => 'devise/sessions#destroy'

    root to: 'books#index'
    resources :subscriptions
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/book.rb
class Book < ApplicationRecord
  has_attached_file :image,
  :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
  :url => "/system/:attachment/:id/:style/:filename",
  :styles => { :medium => "500x500>", :thumb => "120x90#" },
  :default_url => "path to default image"

  validates_attachment_content_type :image, content_type: /\Aimage/

  belongs_to :user

    has_many :libraries
    has_many :added_books, through: :libraries, source: :user
    has_many :coms, :dependent => :destroy
    has_many :taggings
    has_many :tags, through: :taggings

    def self.tagged_with(name)
    Tag.find_by!(name: name).books
  end

  def self.tag_counts
    Tag.select("tags.id, tags.name,count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id, tags.id, tags.name")
 end


  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end


end

app/models/com.rb
class Com < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/image.rb
class Image < ApplicationRecord
  attr_accessible :image, :book
has_attached_file :image
validates_attachment_file_name :image, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/]
end

app/models/library.rb
class Library < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :books, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :books, dependent: :destroy
    has_many :libraries
    has_many :library_additions, through: :libraries, source: :book
  
  def connection
  letsrate_rater
end

def subscribed?
  stripe_subscription_id?
end


end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy library]
  before_action :authenticate_user!, except: %i[index show]

  # GET /books
  # GET /books.json
  def index
    @books = if params[:tag]
               Book.tagged_with(params[:tag])
             else
               Book.all
             end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    # @book = Book.find(params[:id])
    @com = Com.new
    @com.book_id = @book.id
  end

  # GET /books/new
  def new
    @book = current_user.books.build
  end

  # GET /books/1/edit
  def edit; end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.build(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def as_json(options = {})
    super(options.merge(include: [:user, comments: { include: :user }]))
  end

  # add and remove books from/to library
  def library
    type = params[:type]

    if type == 'add'
      current_user.library_additions << @book
      redirect_to library_index_path, notice: "#{@book.title} was added to your library"
    elsif type == 'remove'
      current_user.library_additions.delete(@book)
      redirect_to root_path, notice: "#{@book.title} was removed from your library"
    else
      # type is missing, nothing happens
      redirect_to book_path(@book), notice: 'Looks like nothing happend'
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def book_params
    params.require(:book).permit(:title, :description, :author, :user_id, :image, :tag_list)
  end

  def com_params
    params.require(:com).permit(:body, :user_id)
  end
end

app/controllers/coms_controller.rb
class ComsController < ApplicationController

  def create
    @com = Com.new(com_params)
    @com.book_id = params[:book_id]
    @com.save
    redirect_to book_path(@com.book)

      end


 def as_json(options = {})
    super(options.merge(include: :user))
  end


  def com_params
    params.require(:com).permit(:body, :user_email)
  end


end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
  end

  def new
  end

  def show
    @image = Image.find(params[:id])

  end


  def create
    @image = Image.new(params[:image])
    if @image.save
      redirect_to :action => :show, :id => @image.id
    else
      render 'new'
    end
  end

def image_params
  params.require(:image).permit(:image)
end

  private
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_i, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user_subscribed?
    user_signed_in? && current_user.subscribed?
  end

  def admin?
    user_signed_in? && current_user.admin?
  end

  def subscribed?
    user_signed_in? && current_user.subscribed?
  end


  def tag_cloud(tags, classes)
      max = tags.sort_by(&:count).last
      tags.each do |tag|
        index = tag.count.to_f / Integer(max.count) * (classes.size - 1)
        yield(tag, classes[index.round])
      end
    end


      def titlize(str)
        str.gsub('_', ' ').capitalize
      end
end

app/helpers/books_helper.rb
module BooksHelper
  def user_added_to_library? user, book
    user.libraries.where(user: user, book: book).any?
  end

  end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/coms_helper.rb
module ComsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/books/_book.html.erb
<div class="book">
  <div class="card">
    <div class="card-image">
      <figure class="img">
        <%= image_tag book.image.url(:medium) %>
      </figure>
    </div>
    <div class="card-content">
      <div class="media">
        <div class="media-content">
          <p class="title is-5 is-dark">
            <%= link_to book.title, book_path(book) %>
          </p>
          <p class="subtitle is-6"><%= book.author %></p>
        </div><br>
      </div>
      <div class="button is-small">
        <%= link_to 'about', book_path(book) %>
      </div><br>
      <div class="content">
       <% if user_signed_in? %>

       <% if user_added_to_library?(current_user, book) %>

       <%= link_to 'Remove from library', add_book_path(book, type: "remove"),
       method: :put, class: "button is-small is-danger" %>
       

       <% else %>
       <%= link_to 'Add to library', add_book_path(book, type: "add"),
       method: :put, class: "button is-primary" %>
       <% end %>

       <% else %>
       <%= link_to 'Add to library', new_user_registration_path,
       class: "button is-primary is-fullwidth" %>
       <% end %>
     </div>
   </div>
 </div>
 <div class="controls pt2">
  <% if admin? %>
  <%= link_to 'Edit', edit_book_path(book), class:"button is-small is-rounded " %>
  <%= link_to 'delete', book, method: :delete,
  class:"button is-small is-rounded" %>
  <% end %>
</div>
</div>

app/views/books/_book_controls.html.erb
<% if subscribed? %>

 <% if user_added_to_library?(current_user, book) %>
 <%= image_tag @book.image.url %>

   <%= link_to 'Remove from library', add_book_path(book, type: "remove"), method: :put, class: "button is-danger is-fullwidth" %>

   <% if controller.controller_name == "library" %>
     <%= link_to 'Download', '#', class:"button is-success is-fullwidth mt1" %>
   <% end %>

 <% else %>
   <%= link_to 'Add to library', add_book_path(book, type: "add"), method: :put, class: "button is-link is-fullwidth" %>
 <% end %>

<% else %>
 <%= link_to 'Add to library', new_user_registration_path, class: "button is-link is-fullwidth" %>
<% end %>

app/views/books/_com.html.erb
<div class="comments-container">
	<ul id="comments-list" class="comments-list">
		<li>
			<div class="comment-main-level">
				<div class="comment-box">
					<div class="comment-head">						
						<div class="h2"><b><%= com.user_email %></b></div>
						<span>Posted <%= com.created_at %></span>
					</div>
					<h3>
					<div class="comment-content"><%= com.body %> </div>
					<% if com.created_at != nil  %>
					<% end %>
				</h3>
				</div>
			</div>
		</ul>
	</div>

app/views/books/_form.html.erb
<%= simple_form_for @book, html: { multipart: true } do |f| %>

<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>


<div class="field">
  <div class="control">
    <%= f.input :title, required: true, autofocus: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" } %>
  </div>
</div>
<div class="field">
  <div class="control">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div>
</div>

<div class="field">
  <div class="control">
    <%= f.input :description, required: true, input_html: { class: "textarea"}, wrapper: false, label_html: { class: "label" } %>
  </div>
</div>

<div class="field">
  <div class="control">
    <%= f.input :author, required: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" } %>
  </div>
</div>

<div class="field">
  <div class="control">
    <div class="file">
      <label class="file-label">
        <%= f.input :image, as: :file, required: true, input_html: { class: "file-input" }, wrapper: false, label: false  %>
        <span class="file-cta">
          <span class="file-icon">
            <i class="fa fa-upload"></i>
          </span>
          <span class="file-label">
            Choose an image
          </span>
        </span>
      </label>
    </div>
  </div>
</div>


<%= f.button :submit, class:"button is-dark" %>
<% end %>

<%= form_for @book do |f| %>


<% end %>
<%= render 'shared/errors', object: @book %>

app/views/books/edit.html.erb
<section class="section">
  <div class="columns is-centered">
    <div class="column is-6">
      <h1 class="title is-3">Editing Book</h1>
      <%= render 'form', book: @book %>
    </div>
  </div>
</section>

app/views/books/index.html.erb
<div class="section">
  <div class="container has-text-centered">
    <h1 class="title">
      <i class="fa fa-book"></i> Books available
    </h1>
    
    <center>
      <div id="tag_cloud">
          <% tag_cloud Book.tag_counts, %w[s m l] do |tag, css_class| %>
            <%= link_to tag.name, tag_path(tag.name), class: "button is-dark" %>
          <% end %>
        </div> </center>
  </div>
  <div class="book-grid">
    <%= render @books %>
    <% if @book %>
    <%= link_to (image_tag @book.image.url(:thumb)), book_path(@book) %>
    <% end %>

  </div>

app/views/books/new.html.erb
<section class="section">
  <div class="columns is-centered">
    <div class="column is-6">
      <h1 class="title is-3">New Book</h1>

    <%= render 'form', book: @book %>
  </div>

  </div>
</section>

app/views/books/show.html.erb
<div class="section is-light">
   <div class="columns">
      <div class="column3 is-4">
         <h1>
         <%= image_tag @book.image.url %>
      </div>
      <div class="column3">
         <h1 class="title is-1"><%= @book.title %></h1>
         <h2 class="title is=3"><%= @book.author %></h2>
         <div class="content">
            <%= @book.description %>
         </div>
         <!-- Tags -->   
         <div id="tag_cloud">
            <% @book.tags.each do |tag| %>
            <%= link_to tag.name, tag_path(tag.name), class: "button is-dark"%>
            <% end %>
         </div>
         <% if admin? %>
         <%= link_to 'Edit', edit_book_path(@book), class: "button is-dark is-small" %> 
         <% end %>
      </div>
   </div>


    
      
</div>
<!-- Comments -->
<div class="section">
   <center>
      <h3>Comments (<%= @book.coms.size %>)</h3>
   </center>
   <%= render partial: 'books/com', collection: @book.coms.reverse %>
</div>

   <% if user_signed_in? %>
   <%= render partial: 'coms/form' %>
   <hr />
   <% else %>
   <h1>Only users can comment<br><br></h1>
   <% end %>

app/views/books/tagged.html.erb
@books.tagged

<% render @books.tagged %>

app/views/coms/_form.html.erb
<center>
<% if user_signed_in? %>
<div class="comment-form">
<b>Post a comment</b><br>
<%= simple_form_for [@book, @book.coms.build ] do |f| %>
  <%= f.input :user_email, :label => 'Your name' %>
  <%= f.input :body, :label => 'Review this book' %>
  <%= f.button :submit, "Post", class:"button is-dark" %>
<% end %>
</div>
       
     </center>
     </div>

      <% end %>
</center>

app/views/images/index.html.erb
<h1>Images#index</h1>
<p>Find me in app/views/images/index.html.erb</p>

app/views/images/new.html.erb
<%= form_for(:image, :url => {:action => 'create'}, :html => {:multipart => true}) do |f| %>
  <%= f.file_field :image %>
  <%= f.submit "Upload" %>
<% end %>

app/views/images/show.html.erb
<h1>Images#show</h1>
<p>Find me in app/views/images/show.html.erb</p>