config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :opinions
  post 'images' => 'images#create'
  get 'tags/:tag', to: 'books#index', as: :tag

  get 'images/index'
  get 'images/new'
  get 'images/show'
  resources :books do
    resources :coms
    member do
      get 'tags/:tag',to: "books#index"

      put "add", to: "books#library"
      put "remove", to: "books#library"
      # get "show", to: "books#show"
    end
  end
  resources :library, only:[:index]
  resources :pricing, only:[:index]

  devise_for :users, controllers: { registrations: "registrations" }
  as :user do
    get '/users/sign_out' => 'devise/sessions#destroy'

    root to: 'books#index'
    resources :subscriptions
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/book.rb
class Book < ApplicationRecord
  has_attached_file :image,
  :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
  :url => "/system/:attachment/:id/:style/:filename",
  :styles => { :medium => "500x500>", :thumb => "120x90#" },
  :default_url => "path to default image"

  validates_attachment_content_type :image, content_type: /\Aimage/

  belongs_to :user

    has_many :libraries
    has_many :added_books, through: :libraries, source: :user
    has_many :coms, :dependent => :destroy
    has_many :taggings
    has_many :tags, through: :taggings

    def self.tagged_with(name)
    Tag.find_by!(name: name).books
  end

  def self.tag_counts
    Tag.select("tags.id, tags.name,count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id, tags.id, tags.name")
 end


  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end


end

app/models/com.rb
class Com < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/image.rb
class Image < ApplicationRecord
  attr_accessible :image, :book
has_attached_file :image
validates_attachment_file_name :image, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/]
end

app/models/library.rb
class Library < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :books, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :books, dependent: :destroy
    has_many :libraries
    has_many :library_additions, through: :libraries, source: :book
  
  def connection
  letsrate_rater
end

def subscribed?
  stripe_subscription_id?
end


end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy library]
  before_action :authenticate_user!, except: %i[index show]

  # GET /books
  # GET /books.json
  def index
    @books = if params[:tag]
               Book.tagged_with(params[:tag])
             else
               Book.all
             end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    # @book = Book.find(params[:id])
    @com = Com.new
    @com.book_id = @book.id
  end

  # GET /books/new
  def new
    @book = current_user.books.build
  end

  # GET /books/1/edit
  def edit; end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.build(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def as_json(options = {})
    super(options.merge(include: [:user, comments: { include: :user }]))
  end

  # add and remove books from/to library
  def library
    type = params[:type]

    if type == 'add'
      current_user.library_additions << @book
      redirect_to library_index_path, notice: "#{@book.title} was added to your library"
    elsif type == 'remove'
      current_user.library_additions.delete(@book)
      redirect_to root_path, notice: "#{@book.title} was removed from your library"
    else
      # type is missing, nothing happens
      redirect_to book_path(@book), notice: 'Looks like nothing happend'
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def book_params
    params.require(:book).permit(:title, :description, :author, :user_id, :image, :tag_list)
  end

  def com_params
    params.require(:com).permit(:body, :user_id)
  end
end

app/controllers/coms_controller.rb
class ComsController < ApplicationController

  def create
    @com = Com.new(com_params)
    @com.book_id = params[:book_id]
    @com.save
    redirect_to book_path(@com.book)

      end


 def as_json(options = {})
    super(options.merge(include: :user))
  end


  def com_params
    params.require(:com).permit(:body, :user_email)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user_subscribed?
    user_signed_in? && current_user.subscribed?
  end

  def admin?
    user_signed_in? && current_user.admin?
  end

  def subscribed?
    user_signed_in? && current_user.subscribed?
  end


  def tag_cloud(tags, classes)
      max = tags.sort_by(&:count).last
      tags.each do |tag|
        index = tag.count.to_f / Integer(max.count) * (classes.size - 1)
        yield(tag, classes[index.round])
      end
    end


      def titlize(str)
        str.gsub('_', ' ').capitalize
      end
end

app/helpers/books_helper.rb
module BooksHelper
  def user_added_to_library? user, book
    user.libraries.where(user: user, book: book).any?
  end

  end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/coms_helper.rb
module ComsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'https://js.stripe.com/v3/' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' =>  true %>
  <%= tag :meta, name: "stripe-key", content: Rails.application.secrets.publishable_key %>
  <%# javascript_include_tag "jquery-star-rating" %>
  <%# stylesheet_link_tag "jquery-star-rating" %> 
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>




</head>
<body class="<%= yield (:body_class) %>">
  <% if flash[:notice] %>
  <div class="notification is-success global-notification">
    <p class="notice"><%= notice %></p>
  </div>
  <% end %>

  <% if flash[:alert] %>
  <div class="notification is-danger global-notification">
    <p class="alert"><%= alert %></p>
  </div>
  <% end %>

  <!-- HERO -->   
  <div class="hero-image" >
    <section class="hero">     
      <div class="hero-text">
        <%= link_to root_path do %>
        <h1 class="has-text-white">BookCheq</h1>
        <% end %>
        <h3> Buy a subscription to unlock all the features  
         <a href="<%= pricing_index_path %>" class="button is-button">Pricing</a>
       </h3>
     </div>
   </div>









<!-- carousel -->>



<div class="container">
    <div id="carousel" class="carousel slide" data-ride="carousel" data-interval="false">
        <div class="carousel-inner">
            <div class="carousel-test"></div>

            <div class="carousel-item active">
                <img class="d-block w-100" src="http://via.placeholder.com/1920x1000" alt="">
                <div class="carousel-overlay">
                    <div class="carousel-caption d-none d-md-block">
                        <h2 class="py-2 text-left">Title</h2>
                        <p class="text-left">Lorem ipsum dolor amet cornhole venmo knausgaard locavore listicle cray cloud bread poutine beard flannel irony flexitarian skateboard food truck. Pork belly enamel pin gluten-free blue bottle readymade jianbing thundercats prism, DIY mlkshk single-origin coffee jean shorts sustainable lo-fi. Before they sold out freegan subway tile migas, pug pabst PBRB. Succulents asymmetrical dreamcatcher cronut, kogi poke keytar humblebrag. Flannel fanny pack DIY iceland everyday carry. PBRB chicharrones pitchfork microdosing, raclette direct trade scenester swag artisan messenger bag air plant. Kogi polaroid mumblecore cardigan beard humblebrag poke neutra tilde slow-carb snackwave art party.</p>
                        <p class="text-right">Read More…</p>
                    </div>
                </div>
            </div>

            <div class="carousel-item">
                <img class="d-block w-100" src="http://via.placeholder.com/1920x1000" alt="">
                <div class="carousel-overlay">
                    <div class="carousel-caption d-none d-md-block">
                        <h2 class="py-2 text-left">Title</h2>
                        <p class="text-left">Lorem ipsum dolor amet cornhole venmo knausgaard locavore listicle cray cloud bread poutine beard flannel irony flexitarian skateboard food truck. Pork belly enamel pin gluten-free blue bottle readymade jianbing thundercats prism, DIY mlkshk single-origin coffee jean shorts sustainable lo-fi. Before they sold out freegan subway tile migas, pug pabst PBRB. Succulents asymmetrical dreamcatcher cronut, kogi poke keytar humblebrag. Flannel fanny pack DIY iceland everyday carry. PBRB chicharrones pitchfork microdosing, raclette direct trade scenester swag artisan messenger bag air plant. Kogi polaroid mumblecore cardigan beard humblebrag poke neutra tilde slow-carb snackwave art party.</p>
                        <p class="text-right">Read More…</p>
                    </div>
                </div>
            </div>

            <div class="carousel-item">
                <img class="d-block w-100" src="http://via.placeholder.com/1920x1000" alt="">
                <div class="carousel-overlay">
                    <div class="carousel-caption d-none d-md-block">
                        <h2 class="py-2 text-left">Title</h2>
                        <p class="text-left">Lorem ipsum dolor amet cornhole venmo knausgaard locavore listicle cray cloud bread poutine beard flannel irony flexitarian skateboard food truck. Pork belly enamel pin gluten-free blue bottle readymade jianbing thundercats prism, DIY mlkshk single-origin coffee jean shorts sustainable lo-fi. Before they sold out freegan subway tile migas, pug pabst PBRB. Succulents asymmetrical dreamcatcher cronut, kogi poke keytar humblebrag. Flannel fanny pack DIY iceland everyday carry. PBRB chicharrones pitchfork microdosing, raclette direct trade scenester swag artisan messenger bag air plant. Kogi polaroid mumblecore cardigan beard humblebrag poke neutra tilde slow-carb snackwave art party.</p>
                        <p class="text-right">Read More…</p>
                    </div>
                </div>
            </div>
            
            <div class="carousel-item">
                <img class="d-block w-100" src="http://via.placeholder.com/1920x1000" alt="">
                <div class="carousel-overlay">
                    <div class="carousel-caption d-none d-md-block">
                        <h2 class="py-2 text-left">Title</h2>
                        <p class="text-left">Lorem ipsum dolor amet cornhole venmo knausgaard locavore listicle cray cloud bread poutine beard flannel irony flexitarian skateboard food truck. Pork belly enamel pin gluten-free blue bottle readymade jianbing thundercats prism, DIY mlkshk single-origin coffee jean shorts sustainable lo-fi. Before they sold out freegan subway tile migas, pug pabst PBRB. Succulents asymmetrical dreamcatcher cronut, kogi poke keytar humblebrag. Flannel fanny pack DIY iceland everyday carry. PBRB chicharrones pitchfork microdosing, raclette direct trade scenester swag artisan messenger bag air plant. Kogi polaroid mumblecore cardigan beard humblebrag poke neutra tilde slow-carb snackwave art party.</p>
                        <p class="text-right">Read More…</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="carousel-panel">
            <ol class="carousel-indicators">
                <li data-target="#carousel" data-slide-to="0" class="active"></li>
                <li data-target="#carousel" data-slide-to="1"></li>
                <li data-target="#carousel" data-slide-to="2"></li>
                <li data-target="#carousel" data-slide-to="3"></li>
            </ol>

            <a class="carousel-control-prev align-items-end" href="#carousel" role="button" data-slide="prev">
                <span class="mb-4"><i class="fa fa-angle-left fa-3x"></i></span>
                <span class="sr-only">Previous</span>
            </a>

            <a class="carousel-control-next align-items-end" href="#carousel" role="button" data-slide="next">
                <span class="mb-4"><i class="fa fa-angle-right fa-3x"></i></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>


<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"/>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>













   <!-- NAVBAR -->

   <nav class="navbar is-primary">
    <div class="container">
      <div class="navbar-brand">

        <span class="navbar-burger burger" data-target="navMenu">
          <span></span>
          <span></span>
          <span></span>
        </span>
      </div>
      <div id="navMenu" class="navbar-menu">
        <div class="navbar-end">
          <a href="<%= root_path %>" class="navbar-item">Home</a>

          <% if user_signed_in? %>
          <a href="<%= library_index_path %>" class="navbar-item">My Library</a>
          <a href="<%= edit_user_registration_path %>" class="navbar-item">Edit Profile</a>
          <a href="<%= destroy_user_session_path %>" class="navbar-item">Log Out</a>
          <% else %>
          <a href="<%= pricing_index_path %>" class="navbar-item">Pricing</a>
          <a href="<%= new_user_registration_path %>" class="navbar-item">Sign Up</a>          
          <a href="<%= new_user_session_path %>" class="navbar-item">Log In</a>
          <% end %>
        </div>
      </div>

      <% if admin? %>
      <a href="<%= new_book_path %>" class="navbar-item">New Book</a>
      <% end %>
    </div>
  </nav>
  <script type="text/javascript">
    (function() {
      var burger = document.querySelector('.burger');
      var nav = document.querySelector('#'+burger.dataset.target);
      burger.addEventListener('click', function(){
        burger.classList.toggle('is-active');
        nav.classList.toggle('is-active');
      });
    })();
  </script>

  <%= yield %>
</div>
<div class="footer">
  <p>Anna Młodzik 2018</p>
</div>
</body>


</html>

app/views/layouts/subscribe.html.erb
<!DOCTYPE html>
<html>

  <head>

    <title>Book Library</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'https://js.stripe.com/v3/','data-turbolinks-track': 'reload' %>
    <%= tag :meta, name: "stripe-key", content: Rails.application.secrets.publishable_key %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' =>  true %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">


</head>


<nav class="navbar is-primary">
      <div class="container">
        <div class="navbar-brand">
         
          <span class="navbar-burger burger" data-target="navMenu">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navMenu" class="navbar-menu">
          <div class="navbar-end">
            <a href="<%= root_path %>" class="navbar-item is-active">Home</a>
            
        <% if user_signed_in? %>
       <a href="<%= library_index_path %>" class="navbar-item">My Library</a>
       <a href="<%= edit_user_registration_path %>" class="navbar-item">Edit Profile</a>
       <a href="<%= destroy_user_session_path %>" class="navbar-item">Log Out</a>
          <% else %>
   <a href="<%= pricing_index_path %>" class="navbar-item">Pricing</a>
   <a href="<%= new_user_registration_path %>" class="navbar-item">Sign Up</a>          
    <a href="<%= new_user_session_path %>" class="navbar-item">Log In</a>
    <% end %>
          </div>
        </div>

        <% if admin? %>
          <a href="<%= new_book_path %>" class="navbar-item">New Book</a>
          <% end %>
      </div>
    </nav>
    <script type="text/javascript">
      (function() {
        var burger = document.querySelector('.burger');
        var nav = document.querySelector('#'+burger.dataset.target);
        burger.addEventListener('click', function(){
          burger.classList.toggle('is-active');
          nav.classList.toggle('is-active');
        });
      })();
    </script>
  <body class="<%= yield (:body_class) %>">
    <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>

    <br>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <h3>Some errors were found:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>